# Define build environments
image: Visual Studio 2022

environment:
  PYTHON: "C:\\Python39-x64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install --upgrade pip"
  - "pip install -r src/requirements.txt"

build_script:
  - flet build windows --template gh:flet-dev/flet-build-template -vv

after_build:
  - 7z a MyFletApp-windows.zip %CD%\build
  - copy src/version.txt build/

artifacts:
  - path: MyFletApp-windows.zip

deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true
